### PR TITLE
Update latest and stable to r1.3.1-incubating

### PR DESCRIPTION
**Pull request by aajisaka**
Update the following links:
- https://kyuubi.apache.org/docs/latest/
- https://kyuubi.apache.org/docs/stable/

### CODE REVIEW

**Comment by aajisaka** [comment]
It seems that the GitHub Action (pull request) actually pushed the change to the website: https://github.com/apache/incubator-kyuubi-website/runs/4061225270?check_suite_focus=true#step:5:1117

I think we should skip pushing in the PR.

**Review by ulysses-you — APPROVED** [review]

**Comment by ulysses-you** [comment]
thank you @aajisaka

**Comment by yaooqinn** [comment]
thank you @aajisaka

> It seems that the GitHub Action (pull request) actually pushed the change to the website: https://github.com/apache/incubator-kyuubi-website/runs/4061225270?check_suite_focus=true#step:5:1117
> 
> I think we should skip pushing in the PR.

cc @pan3793，shall we disable the GA trigger for PRs?

**Comment by pan3793** [comment]
Disabled GA on PR on https://github.com/apache/incubator-kyuubi-website/commit/1ff17546c8e6001d86566019920f174a6b16a015

**Pull request merged**
