### PR TITLE
[Kyuubi #2563] Add Chinese Kyuubi website

### PR DESCRIPTION
**Pull request by zhenjiaguo**
Kyuubi website is base on Hugo. Hugo is support multi-language, detail see [Multilingual Mode](https://gohugo.io/content-management/multilingual/).
Translation implements by two ways:

1. [Translation by content directory](https://gohugo.io/content-management/multilingual/#translation-by-content-directory) for markdown files. This way is set different directories for different languages. For instance, `src/en` for English markdown file and `src/zh` for Chinese `markdown` files.
2. [Translation of Strings](https://gohugo.io/content-management/multilingual/#query-basic-translation) for `HTML` files. This way is to define an id and then translation in the corresponding file, like `i18n/zh.toml` for Chinese and `i18n/en.toml` for English.

### CODE REVIEW

**Comment by zhenjiaguo** [comment]
PTAL. @ulysses-you

**Comment by ulysses-you** [comment]
@zhenjiaguo thank you for working on this, it really helpful !

**Review by ulysses-you — APPROVED** [review]
I build locally and looks good

**Comment by turboFei** [comment]
build locally, looks good.
image
Thanks @zhenjiaguo

**Review by turboFei — APPROVED** [review]

**Comment by yaooqinn** [comment]
The figure below shows our vision for the Kyuubi Ecosystem. Some of them have been realized, some in development, and others would not be possible without your help.

does this statement exist on home page before？

**Comment by zhenjiaguo** [comment]
@yaooqinn Yes, I just translation it.

**Pull request merged**
